[variables]
JDK_VERSION = "21"

[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["chmod +x gradlew", "./gradlew shadowJar --no-daemon -x test"]

[start]
cmd = "java -jar build/libs/*-all.jar"
